# Le __init__.py dans models sert à dire à python quels fichiers charger dans ce dossier
from . import parcours_academique
from . import individu
from . import formation
from . import niveau
from . import option
from . import session_niveau
from . import session_parente
from . import prof
from . import tranche_horaire
from . import salle
from . import coefficient
from . import matiere
from . import session_niveau_matiere
from . import session_calendrier
from . import concours
from . import candidat_concours
from . import etudiant
from . import groupe
from . import note
from . import planning